import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased !bg-red-300 border-2 border-black`}
      >
      <header>
        <nav>
          <Link href="/">Home</Link> 
          <Link href="/posts">Posts</Link> 
        </nav>
      </header>        

    {children}
      <footer>
        <p>Copyright 2026. 강은혜. All rights reserved.</p>
      </footer>
      </body>

    </html>
  );
}
