import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header>
        <nav>
          <Link href="/">Home</Link> // 홈페이지 링크: <a></a>태그 대신 사용
          <Link href="/posts">Posts</Link> // 게시글 링크: <a></a>태그 대신 사용
        </nav>
      </header>        

{children}
      </body>
      <footer>
        <p>Copyright 2026. 강은혜. All rights reserved.</p>
      </footer>
    </html>
  );
}
